name: ai-chatbot-prod
services:
  postgres:
    container_name: postgres-prod
    image: pgvector/pgvector:pg17
    command: '-d 1'
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prod
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pgdata-prod: