services:
  postgres:
    container_name: postgres-test
    image: pgvector/pgvector:pg17
    command: '-d 1'
    volumes:
      - ./postgres-test-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: ai-chatbot-test
